### ISSUE TITLE
Implement downloadable dependencies

### ISSUE THREAD

**Issue by jaredmpayne** [jaredmpayne/spur#1]
Implement dependencies that can be downloaded and checked out at a specific version.

## Tasks:

- [x] Create the dependency class.
- [x] Implement ability to clone dependencies from Git repositories specified in the package manifest.
- [x] Implement ability to checkout the package version specified in the package manifest.
- [x] Implement the ability to build dependencies.

**Comment by jaredmpayne** [comment]
`spur` now has the ability to build itself. However, some refactoring is yet to be done. Closing for now.
